on: push

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2.4'
          elixir-version: '1.11.3'
      - name: Check formatting
        run: mix format --check-formatted
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [21.x, 22.x, 23.x]
        elixir: [1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x]
    needs: format
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install deps
        run: mix deps.get
      - name: Run tests
        run: mix test
